export const shadowBanWords = [
  {
    category: 'Ofertas gratuitas',
    data: ['Grátis', 'Sem custo', 'Teste grátis', 'Inscrição gratuita'],
  },
  {
    category: 'Promoções e ofertas',
    data: [
      'Promoção',
      'Oferta imperdível',
      'Oferta limitada',
      'Tempo limitado',
      'Oferta especial',
      'Última chance',
      'Único dia',
      'Apenas para hoje',
      'Desconto secreto',
      'Oferta exclusiva',
      'promoção relâmpago',
      'Oferta VIP',
      'Oferta privada',
    ],
  },
  {
    category: 'Ganhos financeiros',
    data: [
      'Dinheiro fácil',
      'Ganhe dinheiro',
      'Lucro garantido',
      'Aumente seus ganhos',
      'Renda extra',
      'Renda passiva',
      'Investimento sem risco',
      'Milionario',
      'Fortuna',
      'Aposta segura',
      'Enriquecimento rápido',
      'Renda garantida',
      'Ganhe agora',
      '100% garantido',
      'Multiplique seus ganhos',
      'Seu futuro garantido',
      'Milhões em poucos dias',
      'ganhe R$',
      'herdeiro',
    ],
  },
  {
    category: 'Termos financeiros',
    data: [
      'Sem compromisso',
      'Sem custo inicial',
      'Transferência instantânea',
      'Depósito imediato',
      'Pagamento em dinheiro',
    ],
  },
  {
    category: 'Chamadas para ação',
    data: [
      'Compre agora',
      'Clique aqui',
      'Participe agora',
      'clique aqui para resgatar',
    ],
  },
  {
    category: 'Prêmios e seleções',
    data: [
      'Você foi selecionado',
      'Vencedor',
      'Resgate seu prêmio',
      'Bônus exclusivo',
      'Você ganhou',
      'prêmio não reclamado',
      'ATENÇÃO: VOCÊ FOI SELECIONADO!!!',
      'Convite especial',
    ],
  },
  {
    category: 'Urgência',
    data: ['Urgente', 'Contato urgente', 'Ação imediata'],
  },
  {
    category: 'Alertas de conta/segurança',
    data: [
      'Atualize sua conta',
      'Confirmação necessária',
      'Problema na conta',
      'Senha comprometida',
      'Pagamento pendente',
      'Verificação urgente',
      'Confirmação de identidade',
      'Nova política de segurança',
      'Confirme seus dados',
      'Seu cartão foi bloqueado',
      'Seu acesso foi suspenso',
      'Falha no pagamento',
      'Alerta de segurança',
      'Conta invadida',
      'Risco de bloqueio',
      'Novo regulamento',
      'Banco Central',
      'Receita Federal',
      'Seu saldo está negativo',
    ],
  },
  {
    category: 'Saúde e bem-estar',
    data: [
      'Viagra',
      'Cialis',
      'Remédio milagroso',
      'Fórmula secreta',
      'Suplemento natural',
      'Cura definitiva',
      'Emagreça rápido',
      'Sem dieta',
      'Potência sexual',
      'Turbocharge sua energia',
      'Saúde perfeita',
      'Sem esforço',
      'Creme anti-idade',
      'Perda de peso rápida',
      'Tratamento garantido',
      'Reduza rugas',
      'Livre-se das dores',
      'Elimine toxinas',
      'Energia ilimitada',
      'Produto revolucionário',
    ],
  },
  {
    category: 'Oportunidades de negócio',
    data: [
      'Trabalhe de casa',
      'Método infalível',
      'Sistema automatizado',
      'Negócio secreto',
      '100% confiável',
      'Sem precisar vender',
      'Novo sistema de vendas',
      'Seja seu próprio chefe',
      'Clientes ilimitados',
      'Método novo',
      'Planos secretos',
    ],
  },
  {
    category: 'Conteúdo adulto',
    data: [
      'sexo',
      'adulto',
      'prostituição',
      'vídeo íntimo',
      'onlyfans',
      'conteúdo +18',
      'privacy',
      'xvideos',
      'redtube',
      'porno',
      'pornohub',
      'brasileirinhas',
      'novinha',
    ],
  },
  {
    category: 'Encurtadores de link',
    data: [
      'https://bitly.com',
      'https://tinyurl.com',
      'https://is.gd',
      'https://rebrandly.com',
      'https://shorte.st',
      'https://cutt.ly',
      'https://www.bl.ink',
      'https://t2m.io',
      'https://bit.ly',
      'https://ow.ly',
      'https://link.tl',
      'https://encurta.com.br',
      'https://short.io',
      'https://shink.me',
      'https://mande.se',
    ],
  },
  {
    category: 'Palavras ofensivas',
    data: [
      'babaca',
      'imbecil',
      'idiota',
      'retardado',
      'burro',
      'estúpido',
      'palhaço',
      'otário',
      'trouxa',
      'viado',
      'bicha',
      'veado',
      'puta',
      'vadia',
      'prostituta',
      'vagabunda',
      'piranha',
      'cuzão',
      'fdp',
      'filho da puta',
      'arrombado',
      'escroto',
      'merda',
      'caralho',
      'porra',
      'cu',
      'bosta',
      'pau no cu',
      'cornudo',
      'chupetinha',
      'gordo',
      'gorda',
      'feio',
      'feia',
      'fedido',
      'fedida',
      'noob',
      'lixo',
      'desgraçado',
      'desgraçada',
      'maldito',
      'maldita',
      'corno',
      'bocó',
      'panaca',
      'pilantra',
      'safado',
      'safada',
      'canalha',
      'cretino',
      'cretina',
      'jumento',
      'asno',
      'cagão',
      'cagona',
      'bundão',
      'bunda mole',
      'frouxo',
      'covarde',
      'inútil',
      'fracassado',
      'fracassada',
      'ridículo',
      'ridícula',
      'nojento',
      'nojenta',
      'fedorento',
      'fedorenta',
      'boceta',
      'xota',
      'piroca',
      'rola',
      'pênis',
      'buceta',
      'cacetada',
      'cagado',
      'cagada',
      'fode',
      'fuder',
      'vai se fuder',
      'vsf',
      'vtnc',
      'vai tomar no cu',
      'pqp',
      'puta que pariu',
      'filho de uma égua',
      'filho da mãe',
      'cara de pau',
      'sem vergonha',
      'ladrão',
      'ladra',
      'bandido',
      'bandida',
      'maconheiro',
      'seu macaco',
      'drogado',
      'drogada',
      'bebum',
      'alcoolatra',
      'cheirador',
      'nojinho',
      'baitola',
      'sapatão',
      'traveco',
      'degenerado',
      'lixo humano',
      'merdinha',
      'biscate',
      'paspalho',
      'paspalha',
      'corno manso',
      'encostado',
      'parasita',
      'sanguessuga',
      'ralé',
      'ralézinha',
      'ralézinho',
      'ralé da sociedade',
      'ralé do caralho',
      'lixão',
      'escória',
      'lixoso',
      'lixosa',
      'bunda suja',
      'bunda mole',
      'peido',
      'peidei',
      'peida',
      'cagalhão',
      'cagão',
      'cagona',
      'bunda',
      'bostinha',
      'bostão',
      'bostuda',
      'bostudo',
      'bocuda',
      'bocudo',
      'bafiento',
      'bafienta',
      'bafo de cu',
    ],
  },
]
