import { api } from 'src/boot/axios'
import { fakePromise } from 'src/utils/fakePromise.util'
import { ITriggerWord } from 'src/types/sms/ITriggerWord.type'

export async function getAll(): Promise<ITriggerWord[]> {
  /* const { data } = await api.get('/trigger-word/sms/')
  return data */

  await fakePromise(1000)

  const words = [
    'grátis',
    'Sem custo',
    'Teste grátis',
    'Inscrição gratuita',
    'Promoção',
    'Oferta imperdível',
    'Oferta limitada',
    'Tempo limitado',
    'Oferta especial',
    'Última chance',
    'Único dia',
    'Apenas para hoje',
    'Desconto secreto',
    'Oferta exclusiva',
    'promoção relâmpago',
    'Oferta VIP',
    'Oferta privada',
    'Dinheiro fácil',
    'Ganhe dinheiro',
    'Lucro garantido',
    'Aumente seus ganhos',
    'Renda extra',
    'Renda passiva',
    'Investimento sem risco',
    'Milionario',
    'Fortuna',
    'Aposta segura',
    'Enriquecimento rápido',
    'Renda garantida',
    'Ganhe agora',
    '100% garantido',
    'Multiplique seus ganhos',
    'Seu futuro garantido',
    'Milhões em poucos dias',
    'ganhe R$',
    'herdeiro',
    'Sem compromisso',
    'Sem custo inicial',
    'Transferência instantânea',
    'Depósito imediato',
    'Pagamento em dinheiro',
    'Compre agora',
    'Clique aqui',
    'Participe agora',
    'clique aqui para resgatar',
    'Você foi selecionado',
    'Vencedor',
    'Resgate seu prêmio',
    'Bônus exclusivo',
    'Você ganhou',
    'prêmio não reclamado',
    'ATENÇÃO: VOCÊ FOI SELECIONADO!!!',
    'Convite especial',
    'Urgente',
    'Contato urgente',
    'Ação imediata',
    'Atualize sua conta',
    'Confirmação necessária',
    'Problema na conta',
    'Senha comprometida',
    'Pagamento pendente',
    'Verificação urgente',
    'Confirmação de identidade',
    'Nova política de segurança',
    'Confirme seus dados',
    'Seu cartão foi bloqueado',
    'Seu acesso foi suspenso',
    'Falha no pagamento',
    'Alerta de segurança',
    'Conta invadida',
    'Risco de bloqueio',
    'Novo regulamento',
    'Banco Central',
    'Receita Federal',
    'Seu saldo está negativo',
    'Viagra',
    'Cialis',
    'Remédio milagroso',
    'Fórmula secreta',
    'Suplemento natural',
    'Cura definitiva',
    'Emagreça rápido',
    'Sem dieta',
    'Potência sexual',
    'Turbocharge sua energia',
    'Saúde perfeita',
    'Sem esforço',
    'Creme anti-idade',
    'Perda de peso rápida',
    'Tratamento garantido',
    'Reduza rugas',
    'Livre-se das dores',
    'Elimine toxinas',
    'Energia ilimitada',
    'Produto revolucionário',
    'Trabalhe de casa',
    'Método infalível',
    'Sistema automatizado',
    'Negócio secreto',
    '100% confiável',
    'Sem precisar vender',
    'Novo sistema de vendas',
    'Seja seu próprio chefe',
    'Clientes ilimitados',
    'Método novo',
    'Planos secretos',
    'sexo',
    'adulto',
    'prostituição',
    'vídeo íntimo',
    'onlyfans',
    'conteúdo +18',
    'privacy',
    'xvideos',
    'redtube',
    'porno',
    'pornohub',
    'brasileirinhas',
    'novinha',
    'https://bitly.com',
    'https://tinyurl.com',
    'https://is.gd',
    'https://rebrandly.com',
    'https://shorte.st',
    'https://cutt.ly',
    'https://www.bl.ink',
    'https://t2m.io',
    'https://bit.ly',
    'https://ow.ly',
    'https://link.tl',
    'https://encurta.com.br',
    'https://short.io',
    'https://shink.me',
    'https://mande.se',
  ]

  return words.map((v, idx) => ({ id: `${idx}`, name: v }))
}

export async function create(name: string) {
  await api.post('/trigger-word/sms', {
    name,
  })
}

export async function save(id: string, name: string) {
  await api.put(`/trigger-word/sms/${id}`, {
    name,
  })
}

export async function deleteItem(id: string) {
  await api.delete(`/trigger-word/sms/`, {
    data: { id },
  })
}
